(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-page { background-color: #fcfcfc}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-tab-nav li { padding: 0.5em 1.25em 0.5em 1em}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-info .studio-follow-button { width: 40%}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-info .studio-follow-button { padding-bottom: 7px}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-info .studio-follow-button { padding-top: 7px}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-info .studio-follow-button { font-size: 12px}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".button { padding: 0.5em 1em}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-info .studio-title { font-size: 25px}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-info .studio-title { font-weight: 500}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-tab-nav li:active { padding: calc(0.5em) calc(1.25em) calc(0.5em) calc(1em)}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".replies.collapsed > .comment:last-of-type:after { background: none}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-info .studio-description { height: 35rem}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-info { gap: 10px}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".sub-nav li, .sub-nav button { border-radius: 12px}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-tab-nav li { background: transparent}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-info .studio-description.uneditable { background: rgba(174, 182, 191, 0.1)}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".comment.highlighted-comment::before { background: rgba(174, 182, 191, 0.1)}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".compose-comment .textarea-row textarea:not(:focus) { border: 2px solid rgba(0, 0, 0, 0.1)}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".inplace-textarea { background-color: #fff}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-adder-section .studio-adder-row input { padding: 0.5em 1.25em}"})));
(document.head.appendChild(Object.assign(document.createElement('style'), { textContent: ".studio-member-tile { padding: 5px 1px 5px 5px}"})));
